CREATE DATABASE IF NOT EXISTS `shop` DEFAULT CHARACTER SET UTF8;
CREATE TABLE IF NOT EXISTS `shop`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT COMMENT '用户ID' ,
  `username` VARCHAR(50) NOT NULL COMMENT '用户名' ,
  `password` VARCHAR(50) NOT NULL COMMENT '密码(加盐并加密)' ,
  `nickname` VARCHAR(50) NOT NULL COMMENT '昵称' ,
  `email` VARCHAR(50) NOT NULL COMMENT '注册邮箱' ,
  `phone` BIGINT(11) DEFAULT NULL COMMENT '手机号码' ,
  `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
  `utime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间' ,
  `stat` TINYINT NOT NULL DEFAULT 0 COMMENT '用户状态，0为正常，1为受限，2为删除' ,
  PRIMARY KEY (`uid`),
  UNIQUE KEY (`username`)
) ENGINE = InnoDB DEFAULT CHARSET = UTF8;
--
-- CREATE TABLE IF NOT EXISTS `blog`.`kind` (
--   `kid` INT NOT NULL AUTO_INCREMENT ,
--   `name` VARCHAR(10) NOT NULL ,
--   `level` TINYINT NOT NULL DEFAULT 0 COMMENT '优先级' ,
--   `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
--   `utime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间' ,
--   PRIMARY KEY (`kid`)
-- ) ENGINE = InnoDB DEFAULT CHARSET = UTF8;
--
-- CREATE TABLE IF NOT EXISTS `blog`.`blog` (
--   `bid` INT NOT NULL AUTO_INCREMENT ,
--   `title` VARCHAR(30) NOT NULL COMMENT '文章标题' ,
--   `content` TEXT NOT NULL COMMENT '文章内容' ,
--   `kind` INT DEFAULT NULL COMMENT '文章类型',
--   `up` TINYINT NOT NULL DEFAULT 0 COMMENT '是否置顶' ,
--   `uid` INT NOT NULL ,
--   `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
--   `utime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新会议' ,
--   `ptime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '文章发表时间' ,
--   `stat` TINYINT NOT NULL DEFAULT 0 COMMENT '文章状态，0为一般状态，1为私密文章，2为已删除' ,
--   `clicked` INT NOT NULL DEFAULT 0 COMMENT '点击次数' ,
--   `comments` INT NOT NULL DEFAULT 0 COMMENT '评论数' ,
--   PRIMARY KEY (`bid`)
-- ) ENGINE = InnoDB DEFAULT CHARSET = UTF8;
--
-- CREATE TABLE IF NOT EXISTS `blog`.`comment` (
--   `cid` INT NOT NULL AUTO_INCREMENT ,
--   `bid` INT NOT NULL ,
--   `uid` INT NOT NULL ,
--   `content` LONGTEXT NOT NULL ,
--   `ip` VARCHAR(15) NOT NULL COMMENT '评论时的ip地址' ,
--   `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
--   `utime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新会议' ,
--   `stat` TINYINT NOT NULL DEFAULT 0 ,
--   `up` INT NOT NULL DEFAULT 0 COMMENT '点赞次数' ,
--   `down` INT NOT NULL DEFAULT 0 COMMENT '被踩次数' ,
--   PRIMARY KEY (`cid`)
-- ) ENGINE = InnoDB DEFAULT CHARSET = UTF8;
--
-- CREATE TABLE IF NOT EXISTS `blog`.`resource` (
--   `rid` INT NOT NULL AUTO_INCREMENT ,
--   `bid` INT NOT NULL ,
--   `path` LONGTEXT NOT NULL COMMENT '资源存放的路径' ,
--   `type` TINYINT NOT NULL COMMENT '资源类型' ,
--   `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
--   PRIMARY KEY (`rid`)
-- ) ENGINE = InnoDB DEFAULT CHARSET = UTF8;